#!/bin/bash
#chkconfig:2345 80 05 --指定在哪几个级别执行，0一般指关机，
#sudo update-rc.d ss defaults
#6指的是重启，其他为正常启动。80为启动的优先级，05为关闭的优先机
#description:ss service
RETVAL=0

### BEGIN INIT INFO
# Provides: OSSEC HIDS
# Required-Start: $network $remote_fs $syslog $time
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: OSSEC HIDS
### END INIT INFO
if   [   $NODE_HOME   ]; 
then 
echo   "find NODE_HOME" 
else 
echo  "not find NODE_HOME,set it ..."
export NODE_HOME="/opt/node-v0.12.7-linux-x64"
export PATH=$PATH:$NODE_HOME/bin
fi

start(){ 
echo "ss serive ...";
cd /opt/ss;
nohup sslocal > /opt/ss/log.txt 2>&1 & sudo echo $! > /opt/ss/run.pid;
}
stop(){
echo "ss service is stoped...";
pkill -F /opt/ss/run.pid;
}
case $1 in 
start)
start
;;
stop)
stop
;;
esac
exit $RETVAL
